pool:
    vmImage: 'windows-2019'
steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK 5.0.x'
    inputs:
      packageType: 'sdk'
      version: 5.0.x
  - task: DotNetCoreCLI@2
    displayName: 'Pack NuGet'
    inputs:
      packagesToPack: '**/*Avalonia.Lottie.csproj'
      command: custom
      custom: 'pack'
      arguments: 'Avalonia.Lottie/Avalonia.Lottie.csproj -c Release --output $(Build.ArtifactStagingDirectory)/NuGet --version-suffix cibuild$(Build.BuildId)'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Build Artifacts'
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/NuGet'
      artifactName: 'NuGet'
    condition: succeeded()
